---
title: "20180314_Handout"
author: "陳柏銘"
date: "2018/3/14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup}
library("AER")
library("ggplot2")
library("dplyr")
library("knitr")
```

```{r get_dataframe}
data("Journals")
#str(Journals) 
#View(Journals)
Journals
```

```{r}
Journals %>% mutate(citeprice=price/citations) -> journals
#journals
summary(journals) #用來看資料特徵

#price，圖書館訂閱某期刊的價格
#citations，某期刊被引用的次數
#citeprice，期刊引用單價
```

### 因果問句
```{r}
# 引用單價citeprice，如何影響訂閱subs，進到一個類似x影響y，需求的概念
# -0.42是correlation
#
library(psych)
# journals %>% 
#   select(citeprice,subs) %>%
#   pairs.panels()

journals 
journals$subs

# 更理想的寫法，畢竟select這個函數一定有人用過，而且隸屬於兩個以上的套件
journals %>% 
dplyr::select(citeprice,subs) %>% #select: extract column by name
pairs.panels()
```

```{r 取log}
journals %>% 
  dplyr::select(citeprice,subs) %>%
  dplyr::mutate_all(log) %>% #取log使他較接近常態分配，OLS迴歸斜率也較清楚。
  pairs.panels()
```

```{r 計算其他變數與citeprice的相關係數}
# 判斷變數是否為數值類別，先建立函數功能。
is_numeric<-function(x) all(is.numeric(x))
# 計算數數與citeprice的相關係數，先建立函數功能，那要另外建立，是因為有一個citeprice這個變數，我想要先訂下來。
cor_citeprice<-function(x) cor(x,journals$citeprice)

journals %>%  
  select_if(is_numeric) %>%
  summarise_all(cor_citeprice) %>% #summarise是接近敘述統計量的意思
  kable() #kable讓印的表變得比較好看


#回去寫：佐證foundingyear和subs的立足點不同的佐證。correlation
```

```{r 3/20計算foundingyear和subs的相關係數}
library(dplyr)
cor_subs <- function(x){
  cor(x,journals$subs)
}

journals %>%
  select_if(is_numeric) %>% 
  summarise_all(cor_subs) 

#cor(foundingyear, subs) = -0.4073721
#cor(foundingyear, citeprice) = 0.3102098
#cor(citeprice, subs) = -0.4195314

```

```{r 模型比較1}
journals %>% 
  lm(log(subs)~log(citeprice),data=.) #data=.意思是指若在pipe裡面，如果你要放進去的地方，不是在第一個參數的位置。那就可以點，去告訴電腦去把他放到恰當的位置。
#在R裡面，~是建構一個formula，是可以存起來的。那在實證分析上，會傾向先把迴歸式建好，比較不會一直重複打。
```

```{r 模型比較2}
journals %>%
  lm(log(subs)~log(citeprice)+foundingyear,data=.)
```

```{r 模型比較}
journals %>% 
  lm(log(subs)~log(citeprice),data=.) -> model_1
journals %>%
  lm(log(subs)~log(citeprice)+foundingyear,data=.) -> model_2
model_1
model_2

```

```{r}
library(sandwich) #for standard error(就是standard error公式的一個形態，兩端相同，只有中間不同。)
library(lmtest)
library(stargazer) 

#使用vcovHC函數來計算HC1型的異質變異
#（即橫斷面資料且符合隨機抽樣下，的線性迴歸模型）
coeftest(model_1, vcov. = vcovHC, type="HC1") -> model_1_coeftest 
coeftest(model_2, vcov. = vcovHC, type="HC1") -> model_2_coeftest
# vcov. = vcovHC, type="HC1" 是固定的，就是因為他是橫斷面且符合隨機抽樣的類型。他的非對角線都是0，那HC1、HC2是不同的資料型態。遇到就會比較知道。

model_1_coeftest
model_2_coeftest

stargazer(model_1, model_2, 
          se=list(model_1_coeftest[,"Std. Error"], model_2_coeftest[,2]),
          type="text",
          align=TRUE)
#se 指定的standard error算法。se=list(...)不要動。
#[,"Std. Error"]和[,2]的寫法是一樣的目的。寫法不同。
#type="text" 也可以改成"html"
#align就是讓他排版就好看而已。

#查coeftest的help
#查stargazer的help
```

